version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  target-branch: "develop"
  labels:
    - "dependencies"
    - "pip"

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  target-branch: "develop"
  labels:
    - "dependencies"
    - "docker"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  target-branch: "main"
  labels:
    - "dependencies"
    - "github-actions"
