version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "pip"

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "docker"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "github-actions"
