version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "dependencies"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "dependencies"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "dependencies"

  - package-ecosystem: helm
    directory: "/charts/pibot"
    schedule:
      interval: daily
    labels:
      - "dependencies"
