version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: daily
    labels:
      - "dependencies"
    commit-message:
      prefix: deps

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "dependencies"
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "dependencies"
    commit-message:
      prefix: deps

  - package-ecosystem: helm
    directory: "/charts/pibot"
    schedule:
      interval: daily
    labels:
      - "dependencies"
    commit-message:
      prefix: deps
