{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/github",
    [
      "@semantic-release/exec",
      {
        "prepareCmd": "uv version ${nextRelease.version}",
        "successCmd": "touch .release-happened"
      }
    ],
    [
      "@semantic-release/git",
      {
        "assets": ["pyproject.toml","uv.lock"],
        "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }
    ]
  ]
}
