version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9.2

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test-results
            flake8 --exclude=venv* --statistics
            pytest -v --junitxml=test-results/junit.xml --cov=bot
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST cd; mkdir test

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build