apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pibot.name" . }}
type: Opaque
stringData:
  DISCORD_TOKEN: {{ .Values.discord.token | quote }}
  MONGODB_URI: {{ .Values.mongodb.uri | quote }}
  DEEPL_API_KEY: {{ .Values.deepl.apiKey | quote }}
  LOG_LEVEL: {{ .Values.logging.level | quote }}
  COMMAND_SYNC_BEHAVIOR: {{ .Values.bot.settings.commandSyncBehavior | quote }}
  ENABLE_DEV_TOOLS: {{ .Values.bot.settings.enableDevTools | quote }}
