apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pibot.name" . }}
type: Opaque
stringData:
  PIBOT_DISCORD_TOKEN: {{ .Values.pibot.discordToken | quote }}
  PIBOT_MONGODB_URI: {{ .Values.pibot.mongodbUri | quote }}
  PIBOT_SUMMARIZE_CLOUDFLARE_BASE_URL: {{ .Values.pibot.summarize.cloudflare.baseUrl | quote }}
  PIBOT_SUMMARIZE_CLOUDFLARE_TOKEN: {{ .Values.pibot.summarize.cloudflare.token | quote }}
  PIBOT_TRANSLATIONS_DEEPL_API_KEY: {{ .Values.pibot.translations.deepl.apiKey | quote }}
  PIBOT_LOG_LEVEL: {{ .Values.pibot.logLevel | quote }}
  PIBOT_COMMAND_SYNC_BEHAVIOR: {{ .Values.pibot.commandSyncBehavior | quote }}
  PIBOT_ENABLE_DEV_TOOLS: {{ .Values.pibot.enableDevTools | quote }}
