apiVersion: v2
name: pibot
description: Multi-purpose Discord Bot (PiBot)
type: application
version: 4.0.1
appVersion: 4.0.1
keywords:
  - discord
  - bot
home: https://github.com/TobiasGoetz/pibot
sources:
  - https://github.com/TobiasGoetz/pibot
maintainers:
  - name: Tobias Goetz
    email: contact@tobiasgoetz.com
dependencies:
  - name: valkey
    version: 0.11.0
    repository: https://valkey.io/valkey-helm/
    condition: valkey.enabled
