image:
  repository: ghcr.io/tobiasgoetz/pibot
  tag: ""

pibot:
  discordToken: ""
  mongodbUri: ""
  logLevel: INFO
  commandSyncBehavior: global
  enableDevTools: false
  summarize:
    cloudflare:
      baseUrl: ""
      token: ""
  translations:
    deepl:
      apiKey: ""
