name: "PyPI Publish"

on:
  workflow_call:
    inputs: {}
    secrets:
      PYPI_API_TOKEN:
        description: "PyPI API token for publishing"
        required: true

jobs:
  publish:
    permissions:
      contents: read
    runs-on: rpi-cluster
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Install uv
        uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3
        with:
          version: "latest"

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish
